### ISSUE TITLE
Integrate JavaScript linting

### ISSUE THREAD

**Issue by katranci** [whichdigital/webpack-react-workflow#5]
Consider ESLint or JSCS and integrate one of them with Webpack via Karma

**Comment by chris-kobrzak** [comment]
So we found ourselves in a situation where we now have two possible implementations of the linting solution: #19 and #21. I believe we should **stick with ESLint** for now as it simply appears to be a better tool for the job.

Benefits of ESLint:
- not only does it validate code style but it also captures coding errors,
- support for ES6 and JSX was added to ESLint well before JSCS; in fact, the [JSCS docs](http://jscs.info/overview.html#-esnext-e) currently state the support for these two technologies is experimental,
- comprehensive and more declarative rules declaration mechanism: you explicitly define all your rules rather then depending on a third-party preset that you are likely to customise anyway, leading to potentially complex and dispersed set-up,
- the rules set is richer,
- solid documentation.

As for JSCS, the recommended way of using it seems to be in conjunction with JSHint - the tool we are wishing to move away from. [Apparently](https://github.com/eslint/eslint/issues/1774#issuecomment-73293793), JSHint has actually been removing style-related rules as they advise users to resort to JSCS for that. Personally, I don't think we need that degree of de-coupling between these two concerns.
